# Generated by Django 2.2.16 on 2020-10-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reference',
            field=models.URLField(default='blank', help_text='Enter the reference to your Blog Post'),
        ),
    ]
