# Generated by Django 2.2.16 on 2020-10-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20201016_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('01', 'GOT'), ('02', 'Suits'), ('03', 'Dark'), ('04', 'Breaking Bad')], default='O1', max_length=3),
        ),
    ]
