# Generated by Django 2.2.16 on 2020-10-22 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20201022_0611'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
    ]
