# Generated by Django 2.2.16 on 2020-10-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_auto_20201022_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('GOT', 'GOT'), ('Suits', 'Suits'), ('Dark', 'Dark'), ('Breaking Bad', 'Breaking Bad')], default='Null', max_length=20),
        ),
    ]
