# Generated by Django 2.2.16 on 2020-10-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_auto_20201022_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mob',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Mobile Number'),
        ),
    ]
